/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

/**
 *
 * @author Aditi Yadav
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    public MainJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelSystemAdmin = new javax.swing.JLabel();
        labelHospitalAdmin = new javax.swing.JLabel();
        labelcommunityadmin = new javax.swing.JLabel();
        labelPatient = new javax.swing.JLabel();
        labelDoctor = new javax.swing.JLabel();
        BtnSystemAdmin = new javax.swing.JButton();
        BtnHospitalAdmin = new javax.swing.JButton();
        BtnCommunityAdmin = new javax.swing.JButton();
        BtnPatient = new javax.swing.JButton();
        BtnDoctor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setBackground(new java.awt.Color(153, 204, 255));
        labelTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("WELCOME TO AREA INSTANT HEALTHCARE");

        labelSystemAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/System admin1.png"))); // NOI18N
        labelSystemAdmin.setMaximumSize(new java.awt.Dimension(300, 450));

        labelHospitalAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/hosadmin2.png"))); // NOI18N

        labelcommunityadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/communityadmin1.png"))); // NOI18N

        labelPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Patient icon1.png"))); // NOI18N

        labelDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/doctor icon1.png"))); // NOI18N

        BtnSystemAdmin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSystemAdmin.setText("System Administrator");

        BtnHospitalAdmin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnHospitalAdmin.setText("Hospital Administrator");
        BtnHospitalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHospitalAdminActionPerformed(evt);
            }
        });

        BtnCommunityAdmin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnCommunityAdmin.setText("Community Administrator");

        BtnPatient.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnPatient.setText("Patient");

        BtnDoctor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnDoctor.setText("Doctor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSystemAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelHospitalAdmin)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelcommunityadmin)
                            .addComponent(BtnCommunityAdmin))
                        .addGap(18, 18, 18)
                        .addComponent(labelPatient)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelDoctor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(BtnDoctor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BtnSystemAdmin))
                    .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(BtnHospitalAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228)
                        .addComponent(BtnPatient)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHospitalAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPatient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHospitalAdmin)
                    .addComponent(BtnPatient))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSystemAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcommunityadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSystemAdmin)
                            .addComponent(BtnCommunityAdmin)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnDoctor)))
                .addGap(218, 218, 218))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHospitalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHospitalAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHospitalAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCommunityAdmin;
    private javax.swing.JButton BtnDoctor;
    private javax.swing.JButton BtnHospitalAdmin;
    private javax.swing.JButton BtnPatient;
    private javax.swing.JButton BtnSystemAdmin;
    private javax.swing.JLabel labelDoctor;
    private javax.swing.JLabel labelHospitalAdmin;
    private javax.swing.JLabel labelPatient;
    private javax.swing.JLabel labelSystemAdmin;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelcommunityadmin;
    // End of variables declaration//GEN-END:variables
}
